export { default as Chart } from './Chart'
export { default as Axis } from './Axis'
// export { default as Legend } from './Legend'
// export { default as Settings } from './Settings'
// export { default as Choropleth } from './Choropleth'
// export { default as Heatmap } from './Heatmap'
export { default as Histogram } from './Histogram'
export { default as Bar } from './Bar'
// export { default as Scatterplot } from './Scatterplot'
// export { default as ScatterHeatmapHybrid } from './ScatterHeatmapHybrid'
// export { default as Circumshaker } from './Circumshaker'
